language: cpp
sudo: false

matrix:
  include:
    - os: linux
      compiler: gcc
      addons: &gcc7
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7']
      env: CXX_EVAL="g++-7" CC_EVAL="gcc-7" BUILD_TYPE='Release'

    - os: linux
      compiler: gcc
      addons: *gcc7
      env: CXX_EVAL="g++-7" CC_EVAL="gcc-7" BUILD_TYPE='Debug'

    - os: linux
      compiler: clang
      env: BUILD_TYPE='Release' CXX_EVAL="clang++-5.0" CC_EVAL="clang-5.0"
      addons:
        apt:
          sources:
            - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-5.0 main' 
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
            - ubuntu-toolchain-r-test
          packages: ['clang-5.0']

    - os: linux
      compiler: clang
      env: BUILD_TYPE='Debug' CXX_EVAL="clang++-5.0" CC_EVAL="clang-5.0"
      addons:
        apt:
          sources:
            - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-5.0 main' 
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
            - ubuntu-toolchain-r-test
          packages: ['clang-5.0']
          
    - os: osx
      osx_image: xcode8.3
      compiler: clang
      env: CXX_EVAL="clang++" CC_EVAL="clang" BUILD_TYPE='Debug'

    - os: osx
      osx_image: xcode8.3
      compiler: clang
      env: CXX_EVAL="clang++" CC_EVAL="clang" BUILD_TYPE='Release'


before_install:
  - export CXX=$CXX_EVAL
  - export CC=$CC_EVAL
  - export CXXFLAGS="-Werror"

install:
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="https://cmake.org/files/v3.9/cmake-3.9.4-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    elif [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      which cmake || brew install cmake
    fi
before_script:
  - which $CXX
  - $CXX --version
  - cd ${TRAVIS_BUILD_DIR}
  - cmake -H. -B_builds -DBUILD_TESTS=ON
script:
- cmake --build _builds
- cmake --build _builds --target test -- ARGS=--verbose

